### ISSUE TITLE
Add a reference to the colorize gem.

### ISSUE THREAD

**Issue by kohheepeace** [mechanicles/colorize_logs#2]
First of all, this gem is exactly what I was looking for. Very very useful. Thanks a lot. 

I didn't see any reference to the `colorize gem` in the readme, so I wanted to mention it in the issue.
https://github.com/fazibear/colorize

You can use the `colorize gem` option as follows.

`config/initializers/colorize_logs.rb`
```rb
colorize_logs_formatter = ColorizeLogs::Formatter.new

colorize_logs_formatter.configure do
  match(/Started/) do |msg|
    msg.colorize(color: :black, background: :yellow, mode: :bold)
  end

  match(/Processing by/) do |msg|
    msg.colorize(color: :white, background: :light_blue, mode: :bold)
  end

  match(/Rendering layout/) do |msg|
    msg.blue
  end

  match(/Rendering.*within layouts/) do |msg|
    msg.blue
  end
end

::Rails.logger.formatter = colorize_logs_formatter
```

The output will be as follows.
<img width="1149" alt="スクリーンショット 2024-01-03 6 20 25" src="https://github.com/mechanicles/colorize_logs/assets/29557494/fce767cb-65aa-4fc5-8e9a-e385762cf64e">

**Comment by kohheepeace** [comment]
This is actually not an issue, so I will close it. Thanks !

**Comment by kohheepeace** [comment]
Also, the list of supported colors and modes can be found here.

- https://github.com/fazibear/colorize/blob/51c3f67fdd162aa604f653954c871992c6994052/lib/colorize/class_methods.rb

```rb
module Colorize
  module ClassMethods
...
    @@color_codes ||= {
      black:         30,
      red:           31,
      green:         32,
      yellow:        33,
      blue:          34,
      magenta:       35,
      cyan:          36,
      white:         37,
      default:       39,
      light_black:   90,
      light_red:     91,
      light_green:   92,
      light_yellow:  93,
      light_blue:    94,
      light_magenta: 95,
      light_cyan:    96,
      light_white:   97
    }

    @@mode_codes ||= {
      default:          0, # Turn off all attributes
      bold:             1,
      dim:              2,
      italic:           3,
      underline:        4,
      blink:            5,
      blink_slow:       5,
      blink_fast:       6,
      invert:           7,
      hide:             8,
      strike:           9,
      double_underline: 20,
      reveal:           28,
      overlined:        53
    }
...
  end
end
```

**Comment by mechanicles** [comment]
@kohheepeace  Hey, sorry for my late reply. Thanks that you found this gem useful. Also, thanks for sharing your suggestions about improving/highlighting lines using different approach.

**Comment by kohheepeace** [comment]
👍
